- menu_name: "ENGYS Services"

- name: "CFD"
  url: "http://engys.com/services/cfd"
  title: "CFD"

- name: "MDO"
  url: "http://engys.com/services/MDO"
  title: "MDO"

- name: "Adjoint-CFD"
  url: "http://engys.com/services/adjoint-cfd"
  title: "Adjoint-CFD"

- name: "HPC On-Demand"
  url: "http://engys.com/services/hpc-on-demand"
  title: "HPC On-Demand"
